/**
 * `favro execute` CLI Command
 * CLA-1797 / FAVRO-035: Propose & Execute Change System
 *
 * Usage:
 *   favro execute <board> --change-id ch_abc123def456
 *
 * Applies a previously proposed change. Change IDs expire after 10 minutes.
 * Use `favro propose <board> --action "..."` first.
 */

import { Command } from 'commander';
import { createFavroClient } from '../lib/client-factory';
import { logError } from '../lib/error-handler';
import { executeChange, ValidationError } from '../api/propose';

export function registerExecuteCommand(program: Command): void {
  program
    .command('execute <board>')
    .description(
      'Execute a previously proposed change by its change ID.\n\n' +
      'Change IDs are generated by `favro propose` and expire after 10 minutes.\n\n' +
      'Examples:\n' +
      '  favro execute "Sprint 42" --change-id ch_abc123def456\n' +
      '  favro execute boards-1234 --change-id ch_abc123def456 --pretty\n\n' +
      'What previewed is exactly what executes — dry-run accuracy: 100%.'
    )
    .requiredOption('--change-id <id>', 'Change ID from `favro propose` output')
    .option('--pretty', 'Pretty-print JSON output')
    .option('--yes, -y', 'Skip confirmation prompt')
    .option('--force', 'Bypass scope check')
    .action(async (_board: string, options) => {
      const verbose = program.opts()?.verbose ?? false;


      try {
        const client = await createFavroClient();
        
        const { readConfig } = await import('../lib/config');
        const { checkScope, confirmAction } = await import('../lib/safety');
        await checkScope(_board, client, await readConfig(), options.force);
        
        if (!(await confirmAction(`Execute proposed change ${options.changeId} on board ${_board}?`, { yes: options.yes }))) {
          console.log('Aborted.');
          process.exit(0);
        }

        const result = await executeChange(options.changeId, client);

        if (options.pretty) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(JSON.stringify(result));
        }

        if (result.status === 'failed') {
          process.exit(1);
        }
      } catch (error) {
        if (error instanceof ValidationError) {
          console.error(`Error: ${error.message}`);
          if (error.suggestions?.length) {
            console.error(`Suggestions:\n${error.suggestions.map(s => `  - ${s}`).join('\n')}`);
          }
          process.exit(1);
        }
        logError(error, verbose);
        process.exit(1);
      }
    });
}
